### ISSUE TITLE
Decoding frame from H.264 MP4 file

### ISSUE THREAD

**Issue by MikolajMGT** [mike1808/h264decoder#1]
Hello there!
First of all, thank you for publishing this amazing library, I have been struggling with goav and gocv for few days and this project can solve a lot of problems :)
For .h264 extension files everything works fine, but I have problem with decoding data from MP4 H.264 file. I am using same goav fork as you for opening mp4 file and retrieving frames from it. I have following code to get raw data from packet:
```data0 := packet.Data()
buf := make([]byte, packet.GetPacketSize())
start := uintptr(unsafe.Pointer(data0))
	for i := 0; i < packet.GetPacketSize(); i++ {
		elem := *(*uint8)(unsafe.Pointer(start + uintptr(i)))
		buf[i] = elem
}
```
Now when I am passing `buf` to your decoder, received frame slice is unfortunatelly empty. 
After session of debugging, I found out that `AvParserParse2()` from goav, which you use in `parse()` cannot set packet, which stays empty. It looks like it cannot process generated bytes from mp4 file, but for .h264 interestingly there is no problem with this. Does it mean, that for packet from mp4 should I get bytes in different way? Or maybe `AvParserParse2()` is not capable of handling mp4 packets and there is some other method for it?

Console output:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'sample.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 1970-01-01T00:00:00.000000Z
    encoder         : Lavf53.24.2
  Duration: 00:00:05.31, start: 0.000000, bitrate: 1589 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 1205 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 384 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : SoundHandler
2020/04/06 01:43:16 no frames
2020/04/06 01:43:16 no frames
2020/04/06 01:43:16 no frames
...
```

Full code here https://pastebin.com/zATFBJRB, tested with sample.mp4 video from goav project
Regards

**Comment by mike1808** [comment]
Hi @MikolajMGT 
Thanks for using my library. I wrote it to decode raw H.264 output and I am not familiar with any container formats. However, I tried to play with your code and found that mp4 files have some extra metadata. This [stackoverflow question](https://stackoverflow.com/a/55515809) might be helpful!

**Comment by MikolajMGT** [comment]
Hi, thanks for answer. I'm gonna check it out :)
Greetings
